# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a7fbefbb8302a4e612c7fe959159e95af1d2fde5f5935cc005c8a8fd426ebf4c4f9b017f0c77f9cb99646d672538385770a242a844cb3ee7f40a2a475ee80a6

test:
  secret_key_base: 08900561b65e9404fb285867ab0c0c4c627c175d7e0b681ce1333c089d58cbf4fc0ca1b66e382874e7279ce5cbc3e926c27092847dc7da3448ffb4732e0cc314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
